-- create table IF NOT EXISTS public.user_system (
--     id bigint(20) NOT NULL,
--     name varchar(50) NOT NULL,
--     email varchar(50) NOT NULL,
--     username varchar(50) NOT NULL,
--     password varchar(100) NOT NULL,
--     PRIMARY KEY (ID)
-- );
--
-- create table if not exists public.entregador(
--
--     id bigint  primary key  references user_system(id)
--
-- );
--
-- create table if not exists empresa (
--
--     id bigint primary key auto_increment,
--     name varchar(233),
--     cnpj varchar (213)
--
-- );

-- b